lang: en
title: GR Hosting
theme: jekyll-theme-minimal
tagline: Gamer's Cloud
description: "Goob & RubDub's Cloud Services"
author: GoobyFRS == Matt Faulkner
#baseurl: "/goobyfrs.github.io"
url: "https://www.grhost.net"
permalink: pretty
favicon: /assets/img/favicon.ico
logo: /assets/img/logo_color.png

plugins:
  - jekyll-sitemap 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme